[package]
name = "my-lang-rust"
version = "0.1.0"
authors = ["zxwg6329@gmail.com <yuyaisaka87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
